import type { AnnualFinancials } from "@/src/domain/stock";

export type FinancialMetricFormat = "currency" | "percent" | "multiple" | "perShare" | "shares";

export type FinancialMetricKey =
  | "revenue"
  | "grossProfit"
  | "operatingIncome"
  | "ebitda"
  | "netIncome"
  | "operatingCashFlow"
  | "capex"
  | "freeCashFlow"
  | "dilutedEps"
  | "shares"
  | "stockCompensation"
  | "researchAndDevelopment"
  | "buybacks"
  | "dividends"
  | "cash"
  | "longTermDebt"
  | "equity"
  | "grossMargin"
  | "operatingMargin"
  | "ebitdaMargin"
  | "netMargin"
  | "freeCashFlowMargin"
  | "stockCompensationMargin"
  | "priceToEarnings"
  | "fiscalYearEndPrice";

export type FinancialMetricDefinition = {
  key: FinancialMetricKey;
  label: string;
  shortLabel: string;
  format: FinancialMetricFormat;
  color: string;
  description: string;
  value: (annual: AnnualFinancials) => number | null;
};

export type FinancialChartGroup = {
  id: string;
  eyebrow: string;
  title: string;
  description: string;
  metrics: FinancialMetricKey[];
};

const direct = (key: keyof AnnualFinancials) => (annual: AnnualFinancials) => {
  const value = annual[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
};
const margin = (key: keyof AnnualFinancials) => (annual: AnnualFinancials) => {
  const value = annual[key];
  return typeof value === "number" && annual.revenue != null && annual.revenue !== 0
    ? (value / annual.revenue) * 100
    : null;
};

export const financialMetrics: Record<FinancialMetricKey, FinancialMetricDefinition> = {
  revenue: { key: "revenue", label: "Revenue", shortLabel: "Revenue", format: "currency", color: "#e69a36", description: "Reported annual revenue.", value: direct("revenue") },
  grossProfit: { key: "grossProfit", label: "Gross profit", shortLabel: "Gross profit", format: "currency", color: "#d7b54c", description: "Revenue less reported cost of goods or services.", value: direct("grossProfit") },
  operatingIncome: { key: "operatingIncome", label: "Operating income", shortLabel: "Operating", format: "currency", color: "#1b9b91", description: "Profit from operations before financing and taxes.", value: direct("operatingIncome") },
  ebitda: { key: "ebitda", label: "Operating EBITDA proxy", shortLabel: "EBITDA", format: "currency", color: "#4678b7", description: "Operating income plus reported depreciation and amortization; clearly labeled as a proxy.", value: direct("ebitda") },
  netIncome: { key: "netIncome", label: "Net income", shortLabel: "Net income", format: "currency", color: "#7a68b5", description: "Profit attributable after operating and non-operating items.", value: direct("netIncome") },
  operatingCashFlow: { key: "operatingCashFlow", label: "Operating cash flow", shortLabel: "Operating CF", format: "currency", color: "#1b6f74", description: "Cash generated by operating activities.", value: direct("operatingCashFlow") },
  capex: { key: "capex", label: "Capital expenditure", shortLabel: "Capex", format: "currency", color: "#d95d49", description: "Cash paid for property, plant, and equipment, shown as an outflow.", value: (annual) => annual.capex == null ? null : -Math.abs(annual.capex) },
  freeCashFlow: { key: "freeCashFlow", label: "Free cash flow", shortLabel: "Free cash flow", format: "currency", color: "#248267", description: "Operating cash flow less capital expenditure.", value: direct("freeCashFlow") },
  dilutedEps: { key: "dilutedEps", label: "Diluted earnings per share", shortLabel: "Diluted EPS", format: "perShare", color: "#ef6c50", description: "Reported diluted annual earnings per share.", value: direct("dilutedEps") },
  shares: { key: "shares", label: "Shares outstanding", shortLabel: "Shares", format: "shares", color: "#6c7f87", description: "Reported common shares outstanding near fiscal year end.", value: direct("shares") },
  stockCompensation: { key: "stockCompensation", label: "Stock-based compensation", shortLabel: "Stock comp", format: "currency", color: "#b76f92", description: "Reported share-based compensation expense.", value: direct("stockCompensation") },
  researchAndDevelopment: { key: "researchAndDevelopment", label: "Research and development", shortLabel: "R&D", format: "currency", color: "#4678b7", description: "Reported research and development expense when separately disclosed.", value: direct("researchAndDevelopment") },
  buybacks: { key: "buybacks", label: "Share repurchases", shortLabel: "Buybacks", format: "currency", color: "#e69a36", description: "Cash used to repurchase common stock.", value: direct("buybacks") },
  dividends: { key: "dividends", label: "Dividends paid", shortLabel: "Dividends", format: "currency", color: "#1b9b91", description: "Cash dividends paid to shareholders.", value: direct("dividends") },
  cash: { key: "cash", label: "Cash and equivalents", shortLabel: "Cash", format: "currency", color: "#248267", description: "Reported cash and cash equivalents at fiscal year end.", value: direct("cash") },
  longTermDebt: { key: "longTermDebt", label: "Long-term debt", shortLabel: "Long-term debt", format: "currency", color: "#d95d49", description: "Reported long-term debt or the closest comparable filing concept.", value: direct("longTermDebt") },
  equity: { key: "equity", label: "Shareholders’ equity", shortLabel: "Equity", format: "currency", color: "#4678b7", description: "Reported shareholders’ equity at fiscal year end.", value: direct("equity") },
  grossMargin: { key: "grossMargin", label: "Gross margin", shortLabel: "Gross", format: "percent", color: "#e69a36", description: "Gross profit divided by revenue.", value: margin("grossProfit") },
  operatingMargin: { key: "operatingMargin", label: "Operating margin", shortLabel: "Operating", format: "percent", color: "#1b9b91", description: "Operating income divided by revenue.", value: margin("operatingIncome") },
  ebitdaMargin: { key: "ebitdaMargin", label: "EBITDA proxy margin", shortLabel: "EBITDA", format: "percent", color: "#4678b7", description: "Operating EBITDA proxy divided by revenue.", value: margin("ebitda") },
  netMargin: { key: "netMargin", label: "Net margin", shortLabel: "Net", format: "percent", color: "#7a68b5", description: "Net income divided by revenue.", value: margin("netIncome") },
  freeCashFlowMargin: { key: "freeCashFlowMargin", label: "Free-cash-flow margin", shortLabel: "FCF", format: "percent", color: "#248267", description: "Free cash flow divided by revenue.", value: margin("freeCashFlow") },
  stockCompensationMargin: { key: "stockCompensationMargin", label: "Stock compensation / revenue", shortLabel: "Stock comp %", format: "percent", color: "#b76f92", description: "Share-based compensation expense divided by revenue.", value: margin("stockCompensation") },
  priceToEarnings: { key: "priceToEarnings", label: "Fiscal year-end P/E", shortLabel: "P/E", format: "multiple", color: "#ef6c50", description: "Fiscal year-end adjusted price divided by reported diluted EPS; unavailable when EPS is non-positive.", value: direct("priceToEarnings") },
  fiscalYearEndPrice: { key: "fiscalYearEndPrice", label: "Fiscal year-end price", shortLabel: "FY-end price", format: "perShare", color: "#4678b7", description: "Last adjusted close on or before the fiscal year end.", value: direct("fiscalYearEndPrice") },
};

export const financialChartGroups: FinancialChartGroup[] = [
  { id: "growth", eyebrow: "Scale", title: "Growth engine", description: "See whether top-line expansion is translating into gross profit.", metrics: ["revenue", "grossProfit"] },
  { id: "earnings", eyebrow: "Earnings", title: "Profit stack", description: "Move from operating profit through EBITDA proxy to the bottom line.", metrics: ["operatingIncome", "ebitda", "netIncome"] },
  { id: "cash", eyebrow: "Cash conversion", title: "Cash-flow bridge", description: "Operating cash generation, reinvestment, and the cash left after capex.", metrics: ["operatingCashFlow", "capex", "freeCashFlow"] },
  { id: "margins", eyebrow: "Efficiency", title: "Margin architecture", description: "Compare profitability and cash conversion on the same percentage scale.", metrics: ["grossMargin", "operatingMargin", "ebitdaMargin", "netMargin", "freeCashFlowMargin"] },
  { id: "per-share", eyebrow: "Per-share economics", title: "EPS & dilution", description: "Inspect earnings per share alongside the share-count path.", metrics: ["dilutedEps", "shares"] },
  { id: "allocation", eyebrow: "Capital allocation", title: "Owners, talent & reinvestment", description: "Track stock compensation, R&D, buybacks, and dividends without mixing definitions.", metrics: ["stockCompensation", "researchAndDevelopment", "buybacks", "dividends"] },
  { id: "balance", eyebrow: "Balance sheet", title: "Cash, debt & equity", description: "A compact view of liquidity, long-term debt, and reported book equity.", metrics: ["cash", "longTermDebt", "equity"] },
  { id: "valuation", eyebrow: "Valuation", title: "Price paid for earnings", description: "Fiscal year-end price and P/E, with loss years left blank rather than distorted.", metrics: ["priceToEarnings", "fiscalYearEndPrice"] },
];
